---
title: "Embedded SQL Homework"
author: "by Craig W. Slinkman"
date: "December 2, 2015"
output: html_document
---

# Getting the SQLite Chinook Database
In this homework we are going to use the Chinook database.  I have included a fresh copy of the database in this homework folder.  It is found in the zipped file __ChinookDatabase1.4_Sqlite.zip__.  You will need to extract the actual SQLite database from the zip file.  I then rename the database t0 __Chinook.sqlite__ so I always have the original in the zip-file as backup.  

# Requirements
You are to use embedded SQL to perform all required specifications.  You must prove that your database activity was successful by using appropriate embedded queries to show successful results. 

The implemented Chinook data model can be found at  

https://chinookdatabase.codeplex.com/wikipage?title=Chinook_Schema&referringTitle=Home

This will be useful for planning your queries because you will need to navigate through the database.


#Query 1
Use embedded SQL to add the following data data to the database.  You will need to determine the appropriate tables to use as this is a multi-table insertion.  This also means that they need to be carried in a specific order. You will also need to ascertain if the Artist and Al buns are already
in the database.  If so you do not need to add them.

Album                                 | Artist  
--------------------------------------|--------------------  
The Beatles ("The White Album")       | The Beatles 
Fly by Night                          | Rush  
The Freewheelin' Bob Dylan            | Bob Dylan  
Blonde on Blonde                      | Bob Dylan 
Sgt. Pepper's Lonely Hearts Club Band         | The Beatles
Music from the Motion Picture Soundtrack Rush | Eric Clapton

# Query 2
An important aspect of sales management is determining the most valued customers.  We start by joining the Customer and Invoice tables.  We need the Customer identifier and the customer name in last name, comma, first name order.  Computer the customer total orders for each customer and well as customer activity (total number of orders).  Print your results in descending order so that the customers with the highest order total prints first.  Store your results in a data.frame named __Query2__. List only the first 10 rows by using the R-function head.  The R-statement will look like this
$$ head( Query2, 10 )$$

#Query 3
Repeat the analysis of Query 3 but now we want to determine the most profitable album.  Use the same logic.  Instead of customer name use album name.  

#Query 4
Management wants to know the sales revenue generated by each artist because management wants to be able to compute the profitability of each artist.  Use a suitable sort.



